server.port: 8090

logging:
  level:
    org:
      springframework:
        security: debug

spring:
  datasource:
    url: "jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
  jpa:
    defer-datasource-initialization: true
  security:
    user:
      name: user
      password: password

server:
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:server/keystore.p12
    key-store-password: changeit
    protocol: TLS
    enabled-protocols: TLSv1.2

    client-auth: need
    trust-store: classpath:server/truststore.p12
    trust-store-password: changeit